<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="WS-16454" failures="1" tests="2" name="Practice 1" time="0.064" errors="0" timestamp="2024-01-21T23:35:25 IST">
  <testcase classname="test.secondPractice" name="goodMorning" time="0.009"/>
  <testcase classname="test.secondPractice" name="goodNight" time="0.002">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at test.secondPractice.goodNight(secondPractice.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- goodNight -->
  <testcase classname="test.secondPractice" name="goodAfternoon" time="0.0">
    <ignored/>
  </testcase> <!-- goodAfternoon -->
</testsuite> <!-- Practice 1 -->
